export const ActionTypes = {
    //PLATFORM
    SET_PLATFORM: "SET_PLATFORM",
    SELECTED_PLATFORM: "SELECTED_PLATFORM",
    REMOVE_SELECTED_PLATFORM: "REMOVE_SELECTED_PLATFORM",

    // CREATE
    SET_TYPE:"SET_TYPE",
    SELECTED_TYPE:"SELECTED_TYPE",

    
}